name = "Tutorials"
uuid = "cb10daa6-a5e5-4c25-a171-ae181b8ea3c9"
version = "0.4.1"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
OrdinaryDiffEq = "6.111.0"
julia = "1.10"
